//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.29 at 10:36:42 PM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ktelabs_test.ws/tickets", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ws.ktelabs_test.tickets;
